### ISSUE TITLE
Error for paving stones

### ISSUE THREAD

**Issue by tastrax** [BikeCitizens/bikecitizens-taginfo#1]
Hi Folks,

I think the keys and values are incorrect

{
      "key": "surface",
      "value": "paving_stones",
      "object_types": [
        "way"
      ]
    },
    {
      "key": "surface",
      **"value": "paving_stones:20",**
      "object_types": [
        "way"
      ]
    },
    {
      "key": "surface",
      **"value": "paving_stones:30",**
      "object_types": [
        "way"
      ]
    },

Should they actually be 

 {
      **"key": "paving_stones:length",**
      **"value": "20 cm",**
      "object_types": [
        "way"
      ]
    },
    {
      **"key": "paving_stones:length",**
      **"value": "30 cm",**
      "object_types": [
        "way"
      ]
    },

as per https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones

https://taginfo.openstreetmap.org/tags/surface=paving_stones%3A30#projects

**Comment by bc-mihai** [comment]
Hi tastrax,

These are historical tags that used to be documented on the Wiki page and are still present in OpenStreetMap data. In particular, according to [taginfo](https://taginfo.openstreetmap.org/tags/surface=paving_stones%3A30#overview), `paving_stones:30` is still used roughly 10000 times. Our routing engine allows and processes a limited list of `surface` values, including the preferred plain `paving_stones`, but also allowing other values existing in the wild, such as the ones you mentioned.

I've added a "historical" description to these values to reflect that.

Arguably these values should no longer be used when mapping, because the `paving_stones:length` etc. keys are more precise and allow for graceful degradation. In fact, this should be a very good example on why such keys can be useful - if they had been used from the start, we would have not had to add the `paving_stones:30` and `paving_stones:20` values and we would have ignored the `paving_stones:length`/`paving_stones:width` tags, as we don't really process any of the `paving_stones` tags differently.
